version: '3.8'

services:
  # 1. Sabar Redis don Hafiza da Server Cache
  fata-redis:
    image: redis:7-alpine
    container_name: fata_redis_memory
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

  # 2. Babban Enjin na Fata AI (FastAPI + PyTorch)
  fata-api:
    build: .
    container_name: fata_core_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=fata-redis
      - REDIS_PORT=6379
    depends_on:
      - fata-redis
    restart: always

volumes:
  redis_data: